version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fullcycle_i17
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data